#!/bin/bash

# TigerOS script to set GTK dark theme
# Author: Tim Zabel <tjz8659@rit.edu>

path="/home/$USER/.config/gtk-3.0"

if [ ! -f $path/settings.ini ] ; then
cat <<EOF >> $path/settings.ini
[Settings]
gtk-application-prefer-dark-theme=0
EOF
fi

cmd=$( grep "gtk-application-prefer-dark-theme" \
    $path/settings.ini | tail -c 2 )

# Keep dark theme if it's already enabled
if [ $cmd -eq 0 ]
then
    sed -i 's/0/1/' $path/settings.ini
fi

exit 0
