#!/bin/bash

# TigerOS script to set GTK dark theme
# Author: Tim Zabel <tjz8659@rit.edu>

# Variable Declarations
path_pre="/etc/skel/.config/gtk-3.0"
path_user="/home/$USER/.config/gtk-3.0"

cmd=$( grep "gtk-application-prefer-dark-theme" \
    $path_pre/settings.ini | tail -c 2 )

cmd_user=$( grep "gtk-application-prefer-dark-theme" \
    $path_pre/settings.ini | tail -c 2 )

# Create files
if [ ! -f $path_pre/settings.ini ] ; then
cat <<EOF >> $path/settings.ini
[Settings]
gtk-application-prefer-dark-theme=0
EOF
fi

if [ ! -f $path_user/settings.ini ] ; then
cat <<EOF >> $path/settings.ini
[Settings]
gtk-application-prefer-dark-theme=0
EOF
fi

# Leave dark theme enabled
if [ $cmd -eq 0 ]
then
    sed -i 's/0/1/' $path_pre/settings.ini

elif [ $cmd_user -eq 0 ]
then
    sed -i 's/0/1' $path_user/settings.ini
fi

exit 0
