#!/bin/bash

# TigerOS script to set GTK dark theme
# Author: Tim Zabel <tjz8659@rit.edu>
# Deprecated in versions >= 1.0-9

# dark-theme
# 
# Copyright (C) 2018  RIT Linux Users Group  All rights reserved.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.

path="/home/$USER/.config/gtk-3.0"

cmd=$( grep "gtk-application-prefer-dark-theme" \
    $path/settings.ini | tail -c 2 )

# Create files
if [ ! -f $path/settings.ini ] ; then
cat <<EOF >> $path/settings.ini
[Settings]
gtk-application-prefer-dark-theme=0
EOF
fi

# Leave dark theme enabled
if [ $cmd -eq 0 ]
then
    sed -i 's/0/1/' $path/settings.ini
fi

exit 0
