#!/bin/bash

# TigerOS script to set GTK dark theme
# Author: Tim Zabel <tjz8659@rit.edu>
# Not used in tigeros-ui-tweaks-1.0-9

path="/home/$USER/.config/gtk-3.0"

cmd=$( grep "gtk-application-prefer-dark-theme" \
    $path/settings.ini | tail -c 2 )

# Create files
if [ ! -f $path/settings.ini ] ; then
cat <<EOF >> $path/settings.ini
[Settings]
gtk-application-prefer-dark-theme=0
EOF
fi

# Leave dark theme enabled
if [ $cmd -eq 0 ]
then
    sed -i 's/0/1/' $path/settings.ini

exit 0
