#!/bin/bash

# Installs and sets defualt icon theme to the Paper theme
# Author: Tim Zabel <tjz8659@rit.edu>

if [ $EUID != 0 ]
then
    echo "Please run this script as root (sudo $@$0)."
    exit
fi
echo

# Get and translate Real Username to Real User ID
RUID=$(who | awk 'FNR == 1 {print $1}')
RUSER_UID=$(id -u ${RUID})

# Adding the Paper repository
dnf config-manager --add-repo \
    https://download.opensuse.org/repositories/home:snwh:paper/Fedora_25/home:snwh:paper.repo

# Installing the Paper icon theme
dnf install paper-icon-theme

# Enabling Paper theme
sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" \
    gsettings set org.gnome.desktop.interface icon-theme Paper

echo
echo "Paper icon theme enabled."
echo

exit
