#!/bin/bash

# Installs and sets default icon theme to the Paper theme
# Author: Tim Zabel <tjz8659@rit.edu>
# Changed 28/3/2018

if [ $EUID != 0 ]
then
    echo "Please run this script as root (sudo $@$0)."
    exit
fi
echo

# Get and translate Real Username to Real User ID
RUID=$(who | awk 'FNR == 1 {print $1}')
RUSER_UID=$(id -u ${RUID})

# Enabling Paper theme
sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" \
    gsettings set org.gnome.desktop.interface icon-theme Paper

exit 0
